"""empty message

Revision ID: 197a3ab9563f
Revises: 
Create Date: 2019-09-18 00:05:46.022507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197a3ab9563f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('packaging', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Items_Id'), 'Items', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Items_Id'), table_name='Items')
    op.drop_table('Items')
    # ### end Alembic commands ###
