"""empty message

Revision ID: 1ccc112c0338
Revises: 
Create Date: 2020-07-24 12:48:23.622547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccc112c0338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Accounts_email'), 'Accounts', ['email'], unique=True)
    op.create_index(op.f('ix_Accounts_id'), 'Accounts', ['id'], unique=False)
    op.create_index(op.f('ix_Accounts_username'), 'Accounts', ['username'], unique=True)
    op.create_table('InitialCash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InitialCash_id'), 'InitialCash', ['id'], unique=False)
    op.create_table('Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('unit_stock', sa.String(), nullable=True),
    sa.Column('unit_sales', sa.String(), nullable=True),
    sa.Column('sales_per_stock', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('selling_price', sa.Integer(), nullable=True),
    sa.Column('buying_price', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Items_id'), 'Items', ['id'], unique=False)
    op.create_table('staffs',
    sa.Column('_Id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('other_name', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('next_of_kin', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('telephone_contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_Id')
    )
    op.create_table('InitialItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['Items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_InitialItems_id'), 'InitialItems', ['id'], unique=False)
    op.create_table('Stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_purchased', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('purchased_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_purchased'], ['Items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('_Id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sold_by', sa.String(), nullable=True),
    sa.Column('sold_to', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['Items.id'], ),
    sa.PrimaryKeyConstraint('_Id')
    )
    op.create_index(op.f('ix_sales__Id'), 'sales', ['_Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales__Id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('Stocks')
    op.drop_index(op.f('ix_InitialItems_id'), table_name='InitialItems')
    op.drop_table('InitialItems')
    op.drop_table('staffs')
    op.drop_index(op.f('ix_Items_id'), table_name='Items')
    op.drop_table('Items')
    op.drop_index(op.f('ix_InitialCash_id'), table_name='InitialCash')
    op.drop_table('InitialCash')
    op.drop_index(op.f('ix_Accounts_username'), table_name='Accounts')
    op.drop_index(op.f('ix_Accounts_id'), table_name='Accounts')
    op.drop_index(op.f('ix_Accounts_email'), table_name='Accounts')
    op.drop_table('Accounts')
    # ### end Alembic commands ###
