"""empty message

Revision ID: 294ce8db7a90
Revises: 
Create Date: 2020-07-29 19:15:07.221799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294ce8db7a90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InitialItems', sa.Column('sales_quantity', sa.Integer(), nullable=True))
    op.drop_column('InitialItems', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InitialItems', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('InitialItems', 'sales_quantity')
    # ### end Alembic commands ###
