"""empty message

Revision ID: 298497e5cdac
Revises: 8f87745acd64
Create Date: 2019-09-20 03:02:01.359806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298497e5cdac'
down_revision = '8f87745acd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('date_purchased', sa.DateTime(), nullable=True),
    sa.Column('quantity_purchased', sa.Integer(), nullable=True),
    sa.Column('purchased_by', sa.String(), nullable=True),
    sa.Column('purchased_on', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('item_purchased', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_purchased'], ['Items.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_purchases_Id'), 'purchases', ['Id'], unique=False)
    op.create_table('sales',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('date_sold', sa.DateTime(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('unit_sold', sa.String(), nullable=True),
    sa.Column('sold_by', sa.String(), nullable=True),
    sa.Column('sold_on', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('item_sold', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_sold'], ['Items.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_sales_Id'), 'sales', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_Id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_purchases_Id'), table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
