"""creating table of the variou modules

Revision ID: 58eeaf73e8c8
Revises: 
Create Date: 2019-09-21 01:14:48.710522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58eeaf73e8c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('packaging', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Items_Id'), 'Items', ['Id'], unique=False)
    op.create_table('Purchases',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('date_purchased', sa.DateTime(), nullable=True),
    sa.Column('quantity_purchased', sa.Integer(), nullable=True),
    sa.Column('purchased_by', sa.String(), nullable=True),
    sa.Column('purchased_on', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('item_purchased', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_purchased'], ['Items.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Purchases_Id'), 'Purchases', ['Id'], unique=False)
    op.create_table('Sales',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('date_sold', sa.DateTime(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('unit_sold', sa.String(), nullable=True),
    sa.Column('sold_by', sa.String(), nullable=True),
    sa.Column('sold_on', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('item_sold', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_sold'], ['Items.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Sales_Id'), 'Sales', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sales_Id'), table_name='Sales')
    op.drop_table('Sales')
    op.drop_index(op.f('ix_Purchases_Id'), table_name='Purchases')
    op.drop_table('Purchases')
    op.drop_index(op.f('ix_Items_Id'), table_name='Items')
    op.drop_table('Items')
    # ### end Alembic commands ###
