"""empty message

Revision ID: a052aa55d1b8
Revises: 294ce8db7a90
Create Date: 2020-08-03 22:10:26.744576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a052aa55d1b8'
down_revision = '294ce8db7a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Items', 'archived')
    # ### end Alembic commands ###
