"""empty message

Revision ID: c82602242dc7
Revises: 
Create Date: 2019-12-18 19:18:54.160453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82602242dc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemBrands',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('ItemNames',
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name_id')
    )
    op.create_index(op.f('ix_ItemNames_name_id'), 'ItemNames', ['name_id'], unique=False)
    op.create_table('ItemPackaging',
    sa.Column('packaging_id', sa.Integer(), nullable=False),
    sa.Column('packaging', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('packaging_id')
    )
    op.create_table('ItemUnits',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('Staffs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('other_name', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('next_of_kin', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('telephone_contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('State',
    sa.Column('_Id', sa.Integer(), nullable=False),
    sa.Column('states', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_Id'),
    sa.UniqueConstraint('states')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('Images',
    sa.Column('_Id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['State._Id'], ),
    sa.PrimaryKeyConstraint('_Id')
    )
    op.create_table('Items',
    sa.Column('_Id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Integer(), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('packaging', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['ItemBrands.brand_id'], ),
    sa.ForeignKeyConstraint(['name'], ['ItemNames.name_id'], ),
    sa.ForeignKeyConstraint(['packaging'], ['ItemPackaging.packaging_id'], ),
    sa.ForeignKeyConstraint(['unit'], ['ItemUnits.unit_id'], ),
    sa.PrimaryKeyConstraint('_Id')
    )
    op.create_index(op.f('ix_Items__Id'), 'Items', ['_Id'], unique=False)
    op.create_table('Purchases',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('purchased_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
    sa.Column('item_purchased', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_purchased'], ['Items._Id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('Sales',
    sa.Column('_Id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('sold_by', sa.String(), nullable=True),
    sa.Column('sold_on', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('item_sold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_sold'], ['Items._Id'], ),
    sa.PrimaryKeyConstraint('_Id')
    )
    op.create_index(op.f('ix_Sales__Id'), 'Sales', ['_Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sales__Id'), table_name='Sales')
    op.drop_table('Sales')
    op.drop_table('Purchases')
    op.drop_index(op.f('ix_Items__Id'), table_name='Items')
    op.drop_table('Items')
    op.drop_table('Images')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('State')
    op.drop_table('Staffs')
    op.drop_table('ItemUnits')
    op.drop_table('ItemPackaging')
    op.drop_index(op.f('ix_ItemNames_name_id'), table_name='ItemNames')
    op.drop_table('ItemNames')
    op.drop_table('ItemBrands')
    # ### end Alembic commands ###
