"""empty message

Revision ID: fe1119a3e085
Revises: b001f1d19ac2
Create Date: 2020-07-23 20:18:44.021656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1119a3e085'
down_revision = 'b001f1d19ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('buying_price', sa.Integer(), nullable=True))
    op.add_column('Items', sa.Column('selling_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Items', 'selling_price')
    op.drop_column('Items', 'buying_price')
    # ### end Alembic commands ###
